# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 16:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beltapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.date(2017, 5, 31)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_by', to='beltapp.User'),
        ),
        migrations.AddField(
            model_name='quote',
            name='submitted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='beltapp.User'),
        ),
    ]
