# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beltapp', '0002_auto_20170531_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
    ]
